let g:quicktex_c  = {
			\' '   : "\<ESC>:call search('<++>')\<CR>\"_c/+>/e\<CR>",
			\'ñ' : "{\n<+++>\n}",
			\'bo' : "bool <+++>(<++>){\n<++>\n}",
			\'ca' : "switch (<+++>) {\ncase <++>: <++>; break;\ndefault: <++>;\n}",
			\'def' : "#define ",
			\'do' : "do\n<+++>\nwhile(<++>);",
			\'el' : "else ",
			\'f' : "float <+++>;",
			\'fo' : "for ( <+++> ; <++> ; <++> ) <++>",
			\'for' : "for ( <+++> ; <++> ; <++> ) {\n<++>\n}",
			\'ma' : "int main(void){\n<+++>\n\breturn 0;\n}",
			\'inc' : "#include <<+++>.h>",
			\'in' : "int <+++>;",
			\'int' : "int <+++>(<++>){\n<++>\n}",
			\'i' : "if(<+++>) <++>;",
			\'if' : "if(<+++>){\n<++>\n}",
			\'p' : "printf(\"<+++>\");",
			\'pr' : "printf(\"<+++>\", <++>);",
			\'re' : "return <+++>;",
			\'sw' : "switch (<+++>) {\ncase <++>: <++>; break;\ndefault: <++>;\n}",
			\'sc' : "scanf(\"<+++>\", <++>);",
			\'vo' : "void <+++>(<++>){\n<++>\n}",
			\'wh' : "while (<+++>) <++>;",
			\'whi' : "while (<+++>) {\n<++>\n}",
			\}
