let g:quicktex_c  = {
			\' '   : "\<ESC>:call search('<++>')\<CR>\"_c/+>/e\<CR>",
			\'ñ' : "{\n<+++>\n}",
			\'bo' : "bool <+++>(<++>){\n<++>\n}",
			\'ci' : "cin>><+++>;",
			\'cin' : "cin.ignore(numeric_limits<int>::max(),'\n');",
			\'co' : "cout<<\"<+++>\" <++>;",
			\'def' : "#define ",
			\'do' : "do\n<+++>\nwhile(<++>);",
			\'el' : "else ",
			\'f' : "float <+++>;",
			\'flo' : "float <+++>;",
			\'fo' : "for (i=0;i<<+++>;i++) <++>",
			\'foj' : "for (j=0;j<<+++>;j++) <++>",
			\'fun' : "#include \"functions.h\"",
			\'ma' : "int main(){\n<+++>\n\breturn 0;\n}",
			\'in' : "#include <<+++>.h>",
			\'in1' : "#include <<+++>>",
			\'i' : "int <+++>;",
			\'if' : "if(<+++>) <++>;",
			\'if1' : "if(<+++>){\n<++>\n}",
			\'us' : "using namepsace std;",
			\'usi' : "using namepsace std;",
			\'vo' : "void <+++>(<++>){\n<++>\n}",
			\'st' : "string <+++>;",
			\'str' : "string <+++>;",
			\'sy' : "system(\"clear\")",
			\'sys' : "system(\"clear\")",
			\}
