let g:quicktex_cpp  = {
			\' '   : "\<ESC>:call search('<++>')\<CR>\"_c/+>/e\<CR>",
			\'N' : "NULL ",
			\'bo' : "bool <+++>(<++>){\n<++>\n}",
			\'ci' : "cin>><+++>;",
			\'cin' : "cin.ignore(numeric_limits<int>::max(),'\n');",
			\'co' : "cout<<\"<+++>\" <++>;",
			\'do' : "do\n<+++>\nwhile(<++>);",
			\'el' : "else ",
			\'f' : "float <+++>;",
			\'flo' : "float <+++>;",
			\'fo' : "for (i=0;i<<+++>;i++) <++>",
			\'foj' : "for (j=0;j<<+++>;j++) <++>",
			\'fuun' : "#include \"functions.h\"",
			\'ma' : "int main(){\n<+++>\n}",
			\'in' : "#include<<+++>>",
			\'i' : "int <+++>;",
			\'if' : "if(<+++>) <++>;",
			\'if1' : "if(<+++>){\n<++>\n}",
			\'n' : "NULL ",
			\'us' : "using namepsace std;",
			\'usi' : "using namepsace std;",
			\'vo' : "void <+++>(<++>){\n<++>\n}",
			\'st' : "string <+++>;",
			\'str' : "string <+++>;",
			\'sy' : "system(\"clear\")",
			\'sys' : "system(\"clear\")",
			\}
